# These are supported funding model platforms

github: [chakravala]
patreon: dreamscatter
liberapay: chakravala
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
otechie: # Replace with a single Otechie username
custom: https://lulu.com/spotlight/chakravala
